/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AiSourceKind = "expert_insight" | "external_document" | "page" | "plane_work_item";

export type ExpertInsightConfidence = "high" | "low" | "medium";

export type ExpertInsightStatus = "draft" | "published" | "retired";

export type ExpertInsightType = "correction" | "notice" | "recommendation" | "warning";

export type ExpertInsightVoteKind = "helpful" | "not_helpful";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MeetingSource = "mic" | "system";

export type MeetingStatus = "analyzing" | "archived" | "awaiting_review" | "batch_processing" | "batch_submitted" | "completed" | "created" | "deleted" | "deletion_pending" | "documents_generating" | "failed" | "finalizing" | "normalizing_audio" | "partially_failed" | "proposals_generating" | "published" | "recording" | "speakers_pending_review" | "stopping" | "transcribed" | "uploaded" | "uploading";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiChatMessages {
  chatId: string;
  confidence: number | null;
  content: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  groundedSourceCount: number | null;
  id: Generated<string>;
  metadata: Json | null;
  role: string;
  toolCalls: Json | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
  workspaceId: string;
}

export interface AiChats {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AiEmbeddings {
  chunkIndex: number;
  chunkText: string;
  contentHash: string;
  createdAt: Generated<Timestamp>;
  dim: number;
  embedding: string;
  id: Generated<string>;
  metadata: Json | null;
  model: string;
  sourceId: string;
  sourceKind: AiSourceKind;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface ApiKeys {
  clientId: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  lastUsedAt: Timestamp | null;
  name: string | null;
  type: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Attachments {
  aiChatId: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  fileExt: string;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  insightId: string | null;
  mimeType: string | null;
  pageId: string | null;
  spaceId: string | null;
  textContent: string | null;
  tsv: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Audit {
  actorId: string | null;
  actorType: Generated<string>;
  changes: Json | null;
  createdAt: Generated<Timestamp>;
  event: string;
  id: Generated<string>;
  ipAddress: string | null;
  metadata: Json | null;
  resourceId: string | null;
  resourceType: string;
  spaceId: string | null;
  workspaceId: string;
}

export interface AuthAccounts {
  authProviderId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AuthProviders {
  allowSignup: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  groupSync: Generated<boolean>;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  ldapBaseDn: string | null;
  ldapBindDn: string | null;
  ldapBindPassword: string | null;
  ldapConfig: Generated<Json | null>;
  ldapTlsCaCert: string | null;
  ldapTlsEnabled: Generated<boolean | null>;
  ldapUrl: string | null;
  ldapUserAttributes: Generated<Json | null>;
  ldapUserSearchFilter: string | null;
  name: string;
  oidcClientId: string | null;
  oidcClientSecret: string | null;
  oidcIssuer: string | null;
  samlCertificate: string | null;
  samlUrl: string | null;
  settings: Generated<Json | null>;
  type: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Backlinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  sourcePageId: string;
  targetPageId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Billing {
  amount: Int8 | null;
  billingScheme: string | null;
  cancelAt: Timestamp | null;
  cancelAtPeriodEnd: boolean | null;
  canceledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: string | null;
  deletedAt: Timestamp | null;
  endedAt: Timestamp | null;
  id: Generated<string>;
  interval: string | null;
  metadata: Json | null;
  periodEndAt: Timestamp | null;
  periodStartAt: Timestamp;
  planName: string | null;
  quantity: Int8 | null;
  status: string;
  stripeCustomerId: string | null;
  stripeItemId: string | null;
  stripePriceId: string | null;
  stripeProductId: string | null;
  stripeSubscriptionId: string;
  tieredFlatAmount: Int8 | null;
  tieredUnitAmount: Int8 | null;
  tieredUpTo: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Comments {
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  editedAt: Timestamp | null;
  id: Generated<string>;
  lastEditedById: string | null;
  pageId: string;
  parentCommentId: string | null;
  resolvedAt: Timestamp | null;
  resolvedById: string | null;
  selection: string | null;
  spaceId: string;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DocHealthAlertSubscriptions {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lastFiredAt: Timestamp | null;
  spaceId: string | null;
  threshold: number;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface DocHealthSnapshots {
  capturedAt: Timestamp;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  pageCount: number;
  score: number | null;
  scoredPageCount: number;
  signals: Json;
  spaceId: string | null;
  workspaceId: string;
}

export interface ExpertInsights {
  authorDepartment: string | null;
  authorName: string | null;
  authorRole: string | null;
  body: string;
  confidence: Generated<ExpertInsightConfidence>;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  expiresAt: Timestamp | null;
  helpfulCount: Generated<number>;
  id: Generated<string>;
  insightType: ExpertInsightType;
  notHelpfulCount: Generated<number>;
  pageId: string;
  publishedAt: Timestamp | null;
  publishedBy: string | null;
  retiredAt: Timestamp | null;
  spaceId: string;
  spanAnchor: Json | null;
  status: Generated<ExpertInsightStatus>;
  title: string;
  tsv: Generated<string | null>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface ExpertInsightVotes {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  insightId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  vote: ExpertInsightVoteKind;
}

export interface Favorites {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  pageId: string | null;
  spaceId: string | null;
  templateId: string | null;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface FileTasks {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  errorMessage: string | null;
  fileExt: string | null;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  metadata: Json | null;
  pageId: string | null;
  source: string | null;
  spaceId: string | null;
  status: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Groups {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  isDefault: boolean;
  name: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface GroupUsers {
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface IntegrationEvents {
  actorId: string | null;
  causationId: string | null;
  correlationId: string;
  createdAt: Generated<Timestamp>;
  data: Json | null;
  id: Generated<string>;
  publishedAt: Timestamp | null;
  source: string;
  status: Generated<string>;
  subject: string;
  type: string;
  workspaceId: string;
}

export interface IntegrationProjectSpaceMappings {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  mappingKind: Generated<string>;
  planeProjectId: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface IntegrationRelationships {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  inverseRelationType: string;
  lifecycleState: Generated<string>;
  metadata: Json | null;
  provenance: string | null;
  relationType: string;
  sourceType: string;
  sourceUrn: string;
  sourceVersion: Json | null;
  targetType: string;
  targetUrn: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface IntegrationRequirements {
  blockId: string;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  pageId: string;
  state: Generated<string>;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface IntegrationWorkItemStatus {
  completed: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  deletedInSource: Generated<boolean>;
  id: Generated<string>;
  lastDeliveryId: string | null;
  lastEventAt: Timestamp | null;
  planeProjectId: string | null;
  reconciledAt: Timestamp | null;
  sourceUpdatedAt: Timestamp | null;
  state: string | null;
  stateGroup: string | null;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  workItemUrn: string;
  workspaceId: string;
}

export interface IntegrationWebhookDeliveries {
  action: string | null;
  attempts: Generated<number>;
  deliveryId: string;
  error: string | null;
  eventType: string | null;
  id: Generated<string>;
  processedAt: Timestamp | null;
  receivedAt: Generated<Timestamp>;
  signatureValid: Generated<boolean>;
  source: Generated<string>;
  status: Generated<string>;
  subject: string | null;
  workspaceId: string | null;
}

export interface McpOauthClients {
  clientId: string;
  clientName: string | null;
  createdAt: Generated<Timestamp>;
  grantTypes: Generated<Json>;
  id: Generated<string>;
  redirectUris: Generated<Json>;
  responseTypes: Generated<Json>;
  scope: string | null;
  tokenEndpointAuthMethod: Generated<string>;
  workspaceId: string | null;
}

export interface McpOauthRefreshTokens {
  apiKeyId: string;
  clientId: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  resource: string | null;
  rotatedAt: Timestamp | null;
  scope: string | null;
  tokenHash: string;
  userId: string;
  workspaceId: string;
}

export interface MeetingActionProposals {
  automationRuleId: string | null;
  commitment: Generated<string>;
  confidence: number;
  createdAt: Generated<Timestamp>;
  decidedAt: Timestamp | null;
  decidedBy: string | null;
  documentId: string | null;
  duplicateCheck: Generated<Json>;
  editedPayload: Json | null;
  evidence: Json;
  executionResult: Json | null;
  id: Generated<string>;
  idempotencyKey: string;
  kind: string;
  meetingId: string;
  payload: Json;
  reason: string;
  riskLevel: Generated<string>;
  status: Generated<string>;
  targetApp: string;
  title: string;
  transcriptVersion: number;
  updatedAt: Generated<Timestamp>;
  validation: Generated<Json>;
  workspaceId: string;
}

export interface MeetingDocuments {
  contentMarkdown: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  meetingId: string;
  pageId: string | null;
  status: Generated<string>;
  structured: Json;
  templateId: string;
  templateVersion: number;
  title: string;
  transcriptVersion: number;
  updatedAt: Generated<Timestamp>;
}

export interface MeetingProcessingEvents {
  actorId: string | null;
  createdAt: Generated<Timestamp>;
  detail: Generated<Json>;
  event: string;
  fromStatus: string | null;
  id: Generated<string>;
  meetingId: string;
  toStatus: string | null;
}

export interface Meetings {
  aiOutputs: Generated<Json | null>;
  archivedAt: Timestamp | null;
  audioManifest: Generated<Json>;
  audioStoragePrefix: string | null;
  captureKind: Generated<string>;
  consentConfirmedAt: Timestamp | null;
  consentConfirmedBy: string | null;
  cost: Generated<Json>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  durationMs: Generated<number | null>;
  endedAt: Timestamp | null;
  failureReason: string | null;
  id: Generated<string>;
  languageConfig: Generated<Json>;
  legalHold: Generated<boolean>;
  meetingType: Generated<string>;
  meetingTypeConfidence: number | null;
  meetingTypeSource: Generated<string>;
  publishedAt: Timestamp | null;
  retentionUntil: Timestamp | null;
  settings: Generated<Json | null>;
  spaceId: string | null;
  startedAt: Generated<Timestamp>;
  status: Generated<MeetingStatus>;
  title: string;
  transcript: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface MeetingSegments {
  createdAt: Generated<Timestamp>;
  durationMs: number;
  id: Generated<string>;
  meetingId: string;
  sequence: number;
  source: MeetingSource;
  startMs: number;
  text: string;
}

export interface MeetingTemplates {
  createdAt: Generated<Timestamp>;
  definition: Json;
  enabled: Generated<boolean>;
  id: Generated<string>;
  level: Generated<string>;
  meetingType: string;
  ownerId: string | null;
  updatedAt: Generated<Timestamp>;
  version: Generated<number>;
  workspaceId: string;
}

export interface MeetingTranscripts {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  detectedLanguages: Json | null;
  editedFromVersion: number | null;
  error: string | null;
  id: Generated<string>;
  isProvisional: Generated<boolean>;
  kind: string;
  language: string | null;
  meetingId: string;
  processingConfig: Generated<Json>;
  provider: string;
  providerJobId: string | null;
  rawPayloadPath: string | null;
  segments: Generated<Json>;
  speakers: Generated<Json>;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  version: number;
  webhookTokenHash: string | null;
}

export interface Notifications {
  actorId: string | null;
  archivedAt: Timestamp | null;
  commentId: string | null;
  createdAt: Generated<Timestamp>;
  data: Json | null;
  emailedAt: Timestamp | null;
  id: Generated<string>;
  pageId: string | null;
  pageVerificationId: string | null;
  readAt: Timestamp | null;
  spaceId: string | null;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface PageAccess {
  accessLevel: string;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  id: Generated<string>;
  pageId: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface PageBrokenLinks {
  createdAt: Generated<Timestamp>;
  httpStatus: number | null;
  id: Generated<string>;
  kind: string;
  lastCheckedAt: Timestamp;
  pageId: string;
  reason: string;
  spaceId: string;
  targetUrl: string;
  workspaceId: string;
}

export interface PageDuplicates {
  createdAt: Generated<Timestamp>;
  detectedAt: Timestamp;
  duplicateOfPageId: string;
  id: Generated<string>;
  pageId: string;
  similarity: number;
  workspaceId: string;
}

export interface PageHistory {
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  pageId: string;
  slug: string | null;
  slugId: string | null;
  spaceId: string;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  version: number | null;
  workspaceId: string;
}

export interface PagePermissions {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  groupId: string | null;
  id: Generated<string>;
  pageAccessId: string;
  role: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Pages {
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  deletedById: string | null;
  icon: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  lastUpdatedById: string | null;
  ownerId: string | null;
  parentPageId: string | null;
  position: string | null;
  slugId: string;
  spaceId: string;
  textContent: string | null;
  title: string | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
  ydoc: Buffer | null;
}

export interface PageVerifications {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  data: Json | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  mode: string | null;
  pageId: string;
  periodAmount: number | null;
  periodUnit: string | null;
  rejectedAt: Timestamp | null;
  rejectedById: string | null;
  rejectionComment: string | null;
  requestedAt: Timestamp | null;
  requestedById: string | null;
  spaceId: string;
  status: string | null;
  type: Generated<string>;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  verifiedById: string | null;
  workspaceId: string;
}

export interface PageVerifiers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  pageVerificationId: string;
  userId: string;
}

export interface SearchEvents {
  createdAt: Generated<Timestamp>;
  eventType: string;
  id: Generated<string>;
  pageId: string | null;
  query: string;
  resultCount: number | null;
  userId: string | null;
  workspaceId: string;
}

export interface Shares {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  includeSubPages: Generated<boolean | null>;
  key: string;
  pageId: string | null;
  searchIndexing: Generated<boolean | null>;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface SpaceMembers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  groupId: string | null;
  id: Generated<string>;
  role: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Spaces {
  coverImage: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  defaultRole: Generated<string>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  isCritical: Generated<boolean>;
  logo: string | null;
  name: string | null;
  settings: Json | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
  workspaceId: string;
}

export interface Templates {
  collaboratorIds: string[] | null;
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  spaceId: string | null;
  textContent: string | null;
  title: string | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
  ydoc: Buffer | null;
}

export interface UserMfa {
  backupCodes: string[] | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isEnabled: Generated<boolean | null>;
  method: Generated<string>;
  secret: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  deactivatedAt: Timestamp | null;
  deletedAt: Timestamp | null;
  department: string | null;
  email: string;
  emailVerifiedAt: Timestamp | null;
  hasGeneratedPassword: Generated<boolean>;
  id: Generated<string>;
  invitedById: string | null;
  lastActiveAt: Timestamp | null;
  lastLoginAt: Timestamp | null;
  locale: string | null;
  name: string | null;
  password: string | null;
  role: string | null;
  settings: Json | null;
  timezone: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string | null;
}

export interface UserSessions {
  createdAt: Generated<Timestamp>;
  deviceName: string | null;
  expiresAt: Timestamp;
  geoLocation: string | null;
  id: Generated<string>;
  ipAddress: string | null;
  lastActiveAt: Generated<Timestamp>;
  metadata: Json | null;
  revokedAt: Timestamp | null;
  userAgent: string | null;
  userId: string;
  workspaceId: string;
}

export interface UserTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  token: string;
  type: string;
  usedAt: Timestamp | null;
  userId: string;
  workspaceId: string | null;
}

export interface Watchers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  mutedAt: Timestamp | null;
  pageId: string | null;
  spaceId: string;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface WorkspaceInvitations {
  createdAt: Generated<Timestamp>;
  email: string | null;
  groupIds: string[] | null;
  id: Generated<string>;
  invitedById: string | null;
  role: string;
  token: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Workspaces {
  auditRetentionDays: number | null;
  billingEmail: string | null;
  createdAt: Generated<Timestamp>;
  customDomain: string | null;
  defaultRole: Generated<string>;
  defaultSpaceId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  emailDomains: Generated<string[] | null>;
  enforceMfa: Generated<boolean | null>;
  enforceSso: Generated<boolean>;
  hostname: string | null;
  id: Generated<string>;
  licenseKey: string | null;
  logo: string | null;
  name: string | null;
  plan: string | null;
  settings: Json | null;
  status: string | null;
  stripeCustomerId: string | null;
  trashRetentionDays: number | null;
  trialEndAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  aiChatMessages: AiChatMessages;
  aiChats: AiChats;
  aiEmbeddings: AiEmbeddings;
  apiKeys: ApiKeys;
  attachments: Attachments;
  audit: Audit;
  authAccounts: AuthAccounts;
  authProviders: AuthProviders;
  backlinks: Backlinks;
  billing: Billing;
  comments: Comments;
  docHealthAlertSubscriptions: DocHealthAlertSubscriptions;
  docHealthSnapshots: DocHealthSnapshots;
  expertInsights: ExpertInsights;
  expertInsightVotes: ExpertInsightVotes;
  favorites: Favorites;
  fileTasks: FileTasks;
  groups: Groups;
  groupUsers: GroupUsers;
  integrationEvents: IntegrationEvents;
  integrationProjectSpaceMappings: IntegrationProjectSpaceMappings;
  integrationRelationships: IntegrationRelationships;
  integrationRequirements: IntegrationRequirements;
  integrationWebhookDeliveries: IntegrationWebhookDeliveries;
  integrationWorkItemStatus: IntegrationWorkItemStatus;
  mcpOauthClients: McpOauthClients;
  mcpOauthRefreshTokens: McpOauthRefreshTokens;
  meetingActionProposals: MeetingActionProposals;
  meetingDocuments: MeetingDocuments;
  meetingProcessingEvents: MeetingProcessingEvents;
  meetings: Meetings;
  meetingSegments: MeetingSegments;
  meetingTemplates: MeetingTemplates;
  meetingTranscripts: MeetingTranscripts;
  notifications: Notifications;
  pageAccess: PageAccess;
  pageBrokenLinks: PageBrokenLinks;
  pageDuplicates: PageDuplicates;
  pageHistory: PageHistory;
  pagePermissions: PagePermissions;
  pages: Pages;
  pageVerifications: PageVerifications;
  pageVerifiers: PageVerifiers;
  searchEvents: SearchEvents;
  shares: Shares;
  spaceMembers: SpaceMembers;
  spaces: Spaces;
  templates: Templates;
  userMfa: UserMfa;
  users: Users;
  userSessions: UserSessions;
  userTokens: UserTokens;
  watchers: Watchers;
  workspaceInvitations: WorkspaceInvitations;
  workspaces: Workspaces;
}
